import type { Post } from "./types";

const ago = (hours: number) => new Date(Date.now() - hours * 3600_000).toISOString();

// Demo stories shown only while the database is unreachable. Fictional.
export const SEED: Post[] = [
  {
    _id: "demo-1",
    title: "Harbour Street market wins a two-year reprieve after 4,000 sign the petition",
    category: "City",
    img: "assets/img/bench-reader.jpg",
    brief: "The council has dropped plans to clear the Saturday market for a car park, but traders say the fight over rents is only starting.",
    body: "The council has dropped plans to clear the Saturday market for a car park, extending traders' licences to 2028 after a petition passed 4,000 signatures in eleven days.\n\nStallholders packed the public gallery on Tuesday night. Several described lining up before dawn for pitches their parents once held. \"We were never against parking,\" said fruit seller Amara Okafor. \"We were against being told the decision was already made.\"\n\nThe reprieve does not cover rents, which are due to rise 18% in April. Traders' representatives will meet the licensing committee next month to ask for a phased increase.",
    author: "Priya Nair",
    avatar: "assets/img/person-1.jpg",
    date: ago(2),
    top: true,
    trending: true,
  },
  {
    _id: "demo-2",
    title: "Night buses return to the Eastside line from March",
    category: "Transit",
    img: "assets/img/train-doors.jpg",
    brief: "Two routes will run hourly until 3am on weekends, restoring a service cut in 2021.",
    body: "Two night routes will run hourly until 3am on Friday and Saturday from the first weekend of March, restoring a service that was cut in 2021.\n\nThe operator says the trial is funded for six months. Whether it continues depends on how many people ride it, which is why the timetable is being printed at every stop on the line.",
    author: "Daniel Reyes",
    avatar: "assets/img/person-2.jpg",
    date: ago(5),
    top: false,
    trending: false,
  },
  {
    _id: "demo-3",
    title: "What the new rent cap means for a one-bed in Millgate",
    category: "Money",
    img: "assets/img/tablet-charts.jpg",
    brief: "A worked example: how much a typical tenant can be asked to pay from July, and what to do if the letter says otherwise.",
    body: "From July, rent increases on existing tenancies will be limited to 5% a year. For a one-bedroom flat in Millgate at £1,150 a month, that means a ceiling of £1,207.50.\n\nLandlords must give two months' written notice. If your letter asks for more than the cap, you can challenge it for free through the housing tribunal. Keep the letter and your last three rent receipts.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(9),
    top: false,
    trending: false,
  },
  {
    _id: "demo-4",
    title: "The last cinema with a balcony is turning into a repair café",
    category: "Culture",
    img: "assets/img/printing-press.jpg",
    brief: "The Regent closed in September. Volunteers plan to fill the stalls with workbenches and keep the projector.",
    body: "The Regent closed in September after 94 years. This spring, volunteers plan to fill the stalls with workbenches where residents can bring broken toasters, bikes and coats.\n\nThe projector stays. Monthly screenings will fund the roof.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(14),
    top: false,
    trending: false,
  },
  {
    _id: "demo-5",
    title: "Clinic waiting times fall for the first time in three winters",
    category: "Health",
    img: "assets/img/lamppost-reader.jpg",
    brief: "Median wait for a non-urgent appointment is now nine days, down from fourteen.",
    body: "The median wait for a non-urgent appointment at the city's clinics is now nine days, down from fourteen a year ago, according to figures published this week.\n\nThe health board credits a same-day phone triage line. Patient groups say the average hides long waits at two clinics in the north of the city.",
    author: "Priya Nair",
    avatar: "assets/img/person-1.jpg",
    date: ago(20),
    top: false,
    trending: false,
  },
  {
    _id: "demo-6",
    title: "Under-14s league moves indoors as the pitch floods again",
    category: "Sport",
    img: "assets/img/jump.jpg",
    brief: "Fixtures shift to the leisure centre hall while the council decides whether to fix the drainage.",
    body: "Saturday fixtures for the under-14s league will be played five-a-side at the leisure centre after the Meadow Park pitch flooded for the fourth time this winter.\n\nCoaches say the smaller format is working better than expected. The council has yet to say whether it will pay to fix the drains.",
    author: "Daniel Reyes",
    avatar: "assets/img/person-2.jpg",
    date: ago(27),
    top: false,
    trending: false,
  },
  {
    _id: "demo-7",
    title: "Tenants' union counts 212 flats with no working heating",
    category: "City",
    img: "assets/img/printing-press.jpg",
    brief: "Volunteers knocked on 1,900 doors across four estates. The landlord says repairs are scheduled.",
    body: "Volunteers from the tenants' union knocked on 1,900 doors across four estates in January and found 212 flats without working heating.\n\nThe landlord says repairs are scheduled and that 60 have already been fixed. Tenants say they were given the same date in November.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(33),
    top: false,
    trending: true,
  },
  {
    _id: "demo-8",
    title: "Bike lane on Alder Road: six weeks in, what the counters show",
    category: "Transit",
    img: "assets/img/light-wave.jpg",
    brief: "Cycle trips are up 40%. Shops on the street are split on whether that is good for business.",
    body: "Counters on Alder Road logged 40% more cycle trips in the six weeks since the protected lane opened. Car journeys fell by 6%.\n\nShop owners are split. A bakery reports steady trade; a tyre garage says deliveries are harder. The council will publish a full review in the summer.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(40),
    top: false,
    trending: true,
  },
  {
    _id: "demo-9",
    title: "A pension pot for gig couriers? The proposal, in plain English",
    category: "Money",
    img: "assets/img/courier.jpg",
    brief: "A cross-party proposal would add 3% to each delivery fee and pay it into a personal retirement account.",
    body: "A cross-party proposal would add 3% to every delivery fee and pay it into a personal retirement account for the courier who made the trip.\n\nPlatforms say it would raise prices. Couriers' groups say most of them currently have no pension at all.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(52),
    top: false,
    trending: true,
  },
  {
    _id: "demo-10",
    title: "Poets on the 14 bus: a year of verses over the driver's speaker",
    category: "Culture",
    img: "assets/img/lamppost-reader.jpg",
    brief: "Driver Marcus Bell reads one poem a week on the morning run. Passengers now send him their own.",
    body: "Every Monday on the 7:42, driver Marcus Bell reads a poem over the speaker before the first stop. It started as a joke. A year on, passengers slip their own poems into his cab.\n\nHe keeps them in a biscuit tin. The best one so far, he says, was about a missed connection.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(70),
    top: false,
    trending: true,
  },
];
