import type { Post } from "./types";

const ago = (hours: number) => new Date(Date.now() - hours * 3600_000).toISOString();

type StoryInput = Pick<Post, "_id" | "title" | "category" | "img" | "brief" | "body" | "author" | "date"> & Partial<Post>;

const story = (p: StoryInput): Post => ({
  kind: "news",
  caption: "",
  avatar: "",
  top: false,
  trending: false,
  breaking: false,
  views: 0,
  ...p,
});

// Demo stories, used while the database is unreachable and by `npm run seed`. Fictional.
// `views` only apply to the offline demo; the seed script stores 0 so Most read reflects real readers.
const STORIES: StoryInput[] = [
  {
    _id: "demo-1",
    title: "Harbour Street market wins a two-year reprieve after 4,000 sign the petition",
    category: "City",
    img: "assets/img/bench-reader.jpg",
    caption: "Saturday trading on Harbour Street, where some pitches have passed down three generations.",
    views: 1840,
    brief: "The council has dropped plans to clear the Saturday market for a car park, but traders say the fight over rents is only starting.",
    body: "The council has dropped plans to clear the Saturday market for a car park, extending traders' licences to 2028 after a petition passed 4,000 signatures in eleven days.\n\nStallholders packed the public gallery on Tuesday night. Several described lining up before dawn for pitches their parents once held. \"We were never against parking,\" said fruit seller Amara Okafor. \"We were against being told the decision was already made.\"\n\nThe reprieve does not cover rents, which are due to rise 18% in April. Traders' representatives will meet the licensing committee next month to ask for a phased increase.",
    author: "Priya Nair",
    avatar: "assets/img/person-1.jpg",
    date: ago(2),
    top: true,
    trending: true,
  },
  {
    _id: "demo-2",
    title: "Night buses return to the Eastside line from March",
    category: "Transit",
    img: "assets/img/train-doors.jpg",
    caption: "The last Eastside train of the night. From March, two bus routes will take over after midnight.",
    views: 960,
    brief: "Two routes will run hourly until 3am on weekends, restoring a service cut in 2021.",
    body: "Two night routes will run hourly until 3am on Friday and Saturday from the first weekend of March, restoring a service that was cut in 2021.\n\nThe operator says the trial is funded for six months. Whether it continues depends on how many people ride it, which is why the timetable is being printed at every stop on the line.",
    author: "Daniel Reyes",
    avatar: "assets/img/person-2.jpg",
    date: ago(5),
    top: false,
    trending: false,
  },
  {
    _id: "demo-3",
    title: "What the new rent cap means for a one-bed in Millgate",
    category: "Money",
    img: "assets/img/tablet-charts.jpg",
    caption: "Tenants can check any proposed increase against the 5% cap before they sign.",
    views: 1320,
    brief: "A worked example: how much a typical tenant can be asked to pay from July, and what to do if the letter says otherwise.",
    body: "From July, rent increases on existing tenancies will be limited to 5% a year. For a one-bedroom flat in Millgate at £1,150 a month, that means a ceiling of £1,207.50.\n\nLandlords must give two months' written notice. If your letter asks for more than the cap, you can challenge it for free through the housing tribunal. Keep the letter and your last three rent receipts.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(9),
    top: false,
    trending: false,
  },
  {
    _id: "demo-4",
    title: "The last cinema with a balcony is turning into a repair café",
    category: "Culture",
    img: "assets/img/printing-press.jpg",
    caption: "The Regent's projection room will stay, along with its 1950s projector.",
    views: 410,
    brief: "The Regent closed in September. Volunteers plan to fill the stalls with workbenches and keep the projector.",
    body: "The Regent closed in September after 94 years. This spring, volunteers plan to fill the stalls with workbenches where residents can bring broken toasters, bikes and coats.\n\nThe projector stays. Monthly screenings will fund the roof.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(14),
    top: false,
    trending: false,
  },
  {
    _id: "demo-5",
    title: "Clinic waiting times fall for the first time in three winters",
    category: "Health",
    img: "assets/img/lamppost-reader.jpg",
    caption: "Same-day phone triage has cut median waits at most of the city's clinics.",
    views: 380,
    brief: "Median wait for a non-urgent appointment is now nine days, down from fourteen.",
    body: "The median wait for a non-urgent appointment at the city's clinics is now nine days, down from fourteen a year ago, according to figures published this week.\n\nThe health board credits a same-day phone triage line. Patient groups say the average hides long waits at two clinics in the north of the city.",
    author: "Priya Nair",
    avatar: "assets/img/person-1.jpg",
    date: ago(20),
    top: false,
    trending: false,
  },
  {
    _id: "demo-6",
    title: "Under-14s league moves indoors as the pitch floods again",
    category: "Sport",
    img: "assets/img/jump.jpg",
    caption: "Under-14s fixtures move indoors to the leisure centre hall from this weekend.",
    views: 290,
    brief: "Fixtures shift to the leisure centre hall while the council decides whether to fix the drainage.",
    body: "Saturday fixtures for the under-14s league will be played five-a-side at the leisure centre after the Meadow Park pitch flooded for the fourth time this winter.\n\nCoaches say the smaller format is working better than expected. The council has yet to say whether it will pay to fix the drains.",
    author: "Daniel Reyes",
    avatar: "assets/img/person-2.jpg",
    date: ago(27),
    top: false,
    trending: false,
  },
  {
    _id: "demo-7",
    title: "Tenants' union counts 212 flats with no working heating",
    category: "City",
    img: "assets/img/printing-press.jpg",
    caption: "Volunteers recorded every flat without heating in a shared spreadsheet, building by building.",
    views: 1210,
    brief: "Volunteers knocked on 1,900 doors across four estates. The landlord says repairs are scheduled.",
    body: "Volunteers from the tenants' union knocked on 1,900 doors across four estates in January and found 212 flats without working heating.\n\nThe landlord says repairs are scheduled and that 60 have already been fixed. Tenants say they were given the same date in November.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(33),
    top: false,
    trending: true,
  },
  {
    _id: "demo-8",
    title: "Bike lane on Alder Road: six weeks in, what the counters show",
    category: "Transit",
    img: "assets/img/light-wave.jpg",
    caption: "Counters on Alder Road log every bike that passes the protected lane.",
    views: 870,
    brief: "Cycle trips are up 40%. Shops on the street are split on whether that is good for business.",
    body: "Counters on Alder Road logged 40% more cycle trips in the six weeks since the protected lane opened. Car journeys fell by 6%.\n\nShop owners are split. A bakery reports steady trade; a tyre garage says deliveries are harder. The council will publish a full review in the summer.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(40),
    top: false,
    trending: true,
  },
  {
    _id: "demo-9",
    title: "A pension pot for gig couriers? The proposal, in plain English",
    category: "Money",
    img: "assets/img/courier.jpg",
    caption: "Couriers made more than 2 million deliveries in the city last year.",
    views: 640,
    brief: "A cross-party proposal would add 3% to each delivery fee and pay it into a personal retirement account.",
    body: "A cross-party proposal would add 3% to every delivery fee and pay it into a personal retirement account for the courier who made the trip.\n\nPlatforms say it would raise prices. Couriers' groups say most of them currently have no pension at all.",
    author: "Sam Whitfield",
    avatar: "assets/img/person-3.jpg",
    date: ago(52),
    top: false,
    trending: true,
  },
  {
    _id: "demo-10",
    title: "Poets on the 14 bus: a year of verses over the driver's speaker",
    category: "Culture",
    img: "assets/img/lamppost-reader.jpg",
    caption: "Marcus Bell keeps every poem passengers give him in a biscuit tin.",
    views: 720,
    brief: "Driver Marcus Bell reads one poem a week on the morning run. Passengers now send him their own.",
    body: "Every Monday on the 7:42, driver Marcus Bell reads a poem over the speaker before the first stop. It started as a joke. A year on, passengers slip their own poems into his cab.\n\nHe keeps them in a biscuit tin. The best one so far, he says, was about a missed connection.",
    author: "Lena Kowalski",
    avatar: "assets/img/person-4.jpg",
    date: ago(70),
    top: false,
    trending: true,
  },
  {
    _id: "demo-11",
    title: "Storm closes the bay: all ferries suspended until Sunday morning",
    category: "City",
    img: "assets/img/light-wave.jpg",
    caption: "Gusts of up to 90 km/h are forecast along the coast until Saturday night.",
    brief: "The port authority has cancelled every crossing as gusts of up to 90 km/h reach the coast. Extra buses will run on the bridge route.",
    body: "The port authority has suspended all ferry crossings until 7am on Sunday as a storm brings gusts of up to 90 km/h to the coast.\n\nThree extra bus services will run every ten minutes on the bridge route from 4pm. Season tickets will be accepted on all of them.\n\nThe council has asked residents in low-lying streets near the harbour to move cars to higher ground before nightfall.",
    author: "Daniel Reyes",
    avatar: "assets/img/person-2.jpg",
    date: ago(0.6),
    breaking: true,
    views: 2300,
  },
  {
    _id: "demo-12",
    kind: "opinion",
    title: "The market petition proves something the council keeps forgetting: people turn up",
    category: "City",
    img: "assets/img/bench-reader.jpg",
    brief: "Four thousand signatures in eleven days is not a protest. It is a city telling its council what it values.",
    body: "Four thousand signatures in eleven days is not a protest. It is a city telling its council, in the plainest terms available, what it values.\n\nThe market was never only about fruit and second-hand coats. It is one of the few places left where people who would never otherwise meet stand in the same queue every week.\n\nThe reprieve is welcome. But a council that needed a petition to notice this should ask itself what else it is not seeing.",
    author: "Mira Castell",
    avatar: "assets/img/person-5.jpg",
    date: ago(4),
    views: 1110,
  },
  {
    _id: "demo-13",
    kind: "opinion",
    title: "Night buses are not a luxury. They are how this city's workers get home",
    category: "Transit",
    img: "assets/img/train-doors.jpg",
    brief: "Cleaners, cooks and nurses finish work after midnight. For three years, the city acted as if they didn't exist.",
    body: "Cleaners, cooks, nurses and bar staff finish work after midnight. For three years, the city's transport plan acted as if they did not exist.\n\nA six-month trial is a start. But a service that might disappear in September is hard to build a life around.\n\nIf the council wants people to ride the new routes, it should promise now that they will stay.",
    author: "Tomas Adeyemi",
    avatar: "assets/img/person-6.jpg",
    date: ago(11),
    views: 530,
  },
  {
    _id: "demo-14",
    kind: "opinion",
    title: "A 5% rent cap is the least tenants should expect",
    category: "Money",
    img: "assets/img/tablet-charts.jpg",
    brief: "Landlords warn the cap will shrink supply. The last decade suggests the bigger risk is doing nothing.",
    body: "Landlords warn that a cap will shrink the supply of homes to rent. The last decade suggests the bigger risk is doing nothing.\n\nRents in Millgate rose by more than half while wages rose by a fifth. A cap does not fix that gap. It only stops it widening.\n\nThe test of the policy will be enforcement. A rule that tenants are afraid to use is not a rule at all.",
    author: "Hana Lindqvist",
    avatar: "assets/img/person-7.jpg",
    date: ago(26),
    views: 880,
  },
  {
    _id: "demo-15",
    kind: "opinion",
    title: "Keep the projector running: the Regent should stay a little bit of a cinema",
    category: "Culture",
    img: "assets/img/printing-press.jpg",
    brief: "A repair café is a good use for an old cinema. Monthly screenings would make it a great one.",
    body: "A repair café is a good use for an old cinema. Monthly screenings would make it a great one.\n\nThe volunteers' plan already includes them, as a way to pay for the roof. We would go further: put the screenings at the heart of the building, not the edge.\n\nPeople will come to fix a toaster. They will come back to sit in the dark together.",
    author: "Editorial Board",
    date: ago(48),
    views: 260,
  },
];

export const SEED: Post[] = STORIES.map(story);
